#Hibernate Hikari Connection Pool
datasource:
  app:
    driverClassName: com.mysql.jdbc.Driver
    maxPoolSize: 5
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      format_sql: true
      hbm2ddl.auto: v
      current_session_context_class: thread
#Spring
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#Spring boot actuator
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
security:
  basic:
    enabled: false
  enable-csrf: true
server:
  error:
    whitelabel:
      enabled: false