#Hibernate Hikari Connection Pool
datasource:
  app:
    driverClassName: com.mysql.jdbc.Driver
    maxPoolSize: 5
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true
      hbm2ddl.auto: v
      current_session_context_class: thread
#Spring
spring:
  thymeleaf:
    cache: false
    suffix: .jsp

#Spring boot actuator
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
#Flyway
flyway:
  baseline-on-migrate: true
  url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_43121117051449b?reconnect=true
  user: b22000f0ebfe91
  password: 2a4b3328
security:
  basic:
    enabled: false
  enable-csrf: true
server:
  error:
    whitelabel:
      enabled: false