package com.hirs.model.app;

public enum VendorId {

    // FLIGHTS
    FL_AGENT_RU,
    FL_DAVS_RU,
    FL_NABORTU,
    FL_OZON,
    FL_SENTURIA,
    FL_TRIP_RU,
    FL_TRIPSTA_RU,
    FL_GO2SEE_RU,
    FL_TICKETS_RU,
    FL_BOOKANDTRIP_RU,
    FL_SKY_TOURS,
    FL_CLICKANDTRAVEL_RU,
    FL_BILETIX,
    FL_EBOOKERS_COM,
    FL_VAYAMA_COM,
    FL_BILETDV_RU,
    FL_YATURIST,
    FL_BRAVOAVIA_RU,
    FL_AIRBERLIN,

    // KLM group
    FL_KLM,
    FL_AIRFRANCE,
    FL_DELTA,
    FL_IDEALTOUR_RU,
    FL_GOOD_RU,
    FL_EMIRATES_COM,
    FL_TURKISH_AIRLINES,
    FL_ETIHAD_AIRWAYS,
    FL_TIKET_COM,
    FL_CITY_TRAVEL,
    FL_TRAVELPACK_COM,
    FL_LUFTHANSA,
    FL_SWISS_COM,
    FL_SUPERSAVER_RU,
    FL_AIRTICKETS,
    FL_DOUBLETRIP_COM,
    FL_CHEAPOAIR,
    FL_CZECH_AIRLINES,
    FL_SVYAZNOY_TRAVEL,
    FL_VUELING_COM,
    FL_DATRAVEL_COM,
    FL_SKYPICKER_COM,
    FL_AVIAKASSA_RU,
    FL_BILETIK_AERO,
    FL_ONETWOTRIP,
    FL_SUPERKASSA,

    // HOTELS
    HL_EXPEDIA,
    HL_HOTELS24_UA,
    HL_HOTEL_INFO,
    HL_TRAVELMENU_RU,
    HL_OKTOGO_RU,
    HL_BOOKING_COM,
    HL_OZON_TRAVEL,
    HL_EASY_TO_BOOK_COM,
    HL_OSTROVOK_RU,
    HL_CLICK_AND_TRAVEL_RU,
    HL_LATEROOMS_COM,
    HL_OTEL_COM,
    HL_DHR_COM,
    HL_HOTELOPIA,
    HL_HRS_COM,
    HL_VENERE_COM,
    HL_EBOOKERS_COM,
    HL_AGODA_COM,
    HL_GET_A_ROOM_COM,
    HL_HOTEL_DISCOUNT,
    HL_ZLEEPING_HOTELS,
    HL_HOTEL_TRAVEL_COM,
    HL_HOTELS_CLICK_COM,
    HL_HOSTELS_CLUB_COM,
    HL_CITY_TRAVEL,
    HL_SKOOSH_COM,
    HL_SVYAZNOY_TRAVEL,
    HL_HOTELS_COM,
    HL_TIKET_COM,
    HL_ONHOTELS_COM,

    //reviews
    RV_HOLIDAY_CHECK,
    RV_TOPHOTELS_RU,
    RV_FOUR_SQUARE_COM,
    RV_TRIP_ADVISOR,

    // Default vendor for V2 API of B+
    DEFAULT_V2,

    // ====APARTMENTS====
    AP_APARTMENTS_APART,
    AP_DOM2_BY,
    AP_SB,
    AP_9FLATS_COM,
    AP_APARTATOR_RU,
    AP_ONLY_APARTMENTS_COM,
    AP_ROOMORAMA_COM,

    // ====BUS====
    BUS_UNITIKI,
    BUS_BUSFOR,

    // ====TOURS====
    TOUR_OZON_TRAVEL,

    // === RW ====
    RW_UFS_ONLINE_RU,
    RW_ONETWOTRIP
}
