CREATE TABLE IF NOT EXISTS `user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(95) NOT NULL,
  `PASSWORD` VARCHAR(95) NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `VENDOR_ID` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;